const produtos = {
  {cor: 'Plum', grupo: 'Limpeza', items: ['Omo',
    'Veja',
    'Vanish',
    'Esponja',
    'Saco de lixo',
    'Detergente',
    'Álcool']},
  {cor: 'LightSalmon', grupo: 'Frutas e Verduras', items: ['Cebola',
    'Tomate',
    'Aspargos',
    'Alho',
    'Alface',
    'Legumes p/ Sopa',
    'Banana',
    'Maçã',
    'Abacate']},
  {cor: 'PaleGreen', grupo: 'Massas e Cereais', items: ['Arroz',
    'Kome',
    'Macarrão',
    'Farinha de Trigo',
    'Tofu',
    'Massa de Tomate']},
  {cor: 'Aqua', grupo: 'Frios e Congelados', items: ['Presunto',
    'Peito de Peru',
    'Mussarela',
    'Waffle',
    'Pizza',
    'Massa de Pizza',
    'Iogurte',
    'Actimel',
    'Suco de Laranja',
    'Suco de Uva']}
};
